name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - uses: maxheld83/pandoc@v2
        with:
          args: "report/report.md -o report/report.pdf --resource-path report/"
      - name: Post Build
        run: npm run postbuild-pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
